# ok
name: Update Code Quality Image
on:
  push:
    paths:
      - "containers/code-quality/Dockerfile"
      - ".github/workflows/ci-update-code-quality-image.yaml"
      - ".pre-commit-config.yaml"

jobs:
  build:
    uses: exploring-gh-organizations/.github/.github/workflows/shared-ci-docker-build-push.yaml@main
    with:
      repo-name: "code-quality"
      context: "."
      dockerfile: "containers/code-quality/Dockerfile"
      build-args: |
        PRECOMMIT_CONFIG_PATH=.pre-commit-config.yaml
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
