name: Update Code Quality Image

on:
  push:
    paths:
      - "containers/code-quality/Dockerfile"
      - ".github/workflows/ci-update-code-quality-image.yaml"
      - ".pre-commit-config.yaml"
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    name: 🏗️ Build Code Quality Image
    uses: exploring-gh-organizations/called/.github/workflows/shared-ci-docker-build-push.yaml@main
    with:
      repo-name: "code-quality"
      context: "."
      dockerfile: "containers/code-quality/Dockerfile"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
