name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  quality:
    name: Code Quality
    uses: exploring-gh-organizations/called/.github/workflows/shared-ci-code-quality.yaml@main
    # Everything is pre-baked in the container, just run!
    # Optional: skip specific hooks if needed
    # with:
    #   skip-hooks: "oxipng,gitleaks"
